=== AdiVillanueva/itprog/php files/dishes.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="dishes">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="dish" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="name">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                    <xsd:minLength value="1"/> 
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="category">
                <xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="Mains"/>
						<xsd:enumeration value="Sides"/>
						<xsd:enumeration value="Drinks"/>
					</xsd:restriction>
				</xsd:simpleType>
              </xsd:element>
              <xsd:element name="price">
				<xsd:simpleType>
					<xsd:restriction base="xsd:float">
						<xsd:minExclusive value="0"/>
					</xsd:restriction>
				</xsd:simpleType>
			  </xsd:element>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== AdiVillanueva/itprog/php files/xml_testing.xml
<?xml version="1.0"?>
<dishes xsi="http://www.w3.org/2001/XMLSchema-instance" noNamespaceSchemaLocation="dishes.xsd">
<dish>
    <name>try</name>
    <category>Mains</category>
    <price>70</price>
</dish>

<dish>
    <name>catch</name>
    <category>Drinks</category>
    <price>70</price>
</dish>
</dishes>

=== AdiVillanueva/itprog/php files/dishes_xmldata.xml
<?xml version="1.0"?>
<dishes xsi="http://www.w3.org/2001/XMLSchema-instance" noNamespaceSchemaLocation="dishes.xsd">
<dish>
    <name>Spaghetti</name>
    <category>Mains</category>
    <price>450</price>
</dish>
<dish>
    <name>Steak</name>
    <category>Mains</category>
    <price>450</price>
</dish>
<dish>
    <name>Lemonade</name>
    <category>Drinks</category>
    <price>100</price>
</dish>
<dish>
    <name>Iced Tea</name>
    <category>Drinks</category>
    <price>100</price>
</dish>
<dish>
    <name>Fries</name>
    <category>Sides</category>
    <price>200</price>
</dish>
</dishes>
